### ISSUE TITLE
Android build failed on latest React Native version 0.74.2

### ISSUE THREAD

**Issue by Vishujain1** [ccnnde/react-native-simple-openvpn#64] opened 2024-06-13 09:32 UTC
**Bug description:**
Android build failed on latest React Native version 0.74.2

**Error:**
> Task :vpnLib:compileUiDebugJavaWithJavac FAILED
43 actionable tasks: 5 executed, 38 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:37: error: cannot find symbol
    static final RemoteCallbackList<IStatusCallbacks> mCallbacks =
                                    ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusService
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:61: error: package IServiceStatus does not exist
    private static final IServiceStatus.Stub mBinder = new IServiceStatus.Stub() {
                                       ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:231: error: cannot find symbol
    private static void sendUpdate(IStatusCallbacks broadcastItem,
                                   ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusService
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:69: error: cannot find symbol
public class OpenVPNService extends VpnService implements StateListener, Callback, ByteCountListener, IOpenVPNServiceInternal {
                                                                                                      ^
  symbol: class IOpenVPNServiceInternal
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:31: error: cannot find symbol
    private final IStatusCallbacks mCallback = new IStatusCallbacks.Stub() {
                  ^
  symbol:   class IStatusCallbacks
  location: class StatusListener
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:22: error: cannot find symbol
import de.blinkt.openvpn.api.ExternalCertificateProvider;
                            ^
  symbol:   class ExternalCertificateProvider
  location: package de.blinkt.openvpn.api
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:248: error: cannot find symbol
        private final ExternalCertificateProvider service;
                      ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:252: error: cannot find symbol
                                                 ExternalCertificateProvider service) {
                                                 ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:263: error: cannot find symbol
        public ExternalCertificateProvider getService() {
               ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/LaunchVPN.java:38: error: cannot find symbol
import de.blinkt.openvpn.core.IServiceStatus;
                             ^
  symbol:   class IServiceStatus
  location: package de.blinkt.openvpn.core
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:42: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:56: error: cannot find symbol
    final RemoteCallbackList<IOpenVPNStatusCallback> mCallbacks =
                             ^
  symbol:   class IOpenVPNStatusCallback
  location: class ExternalOpenVPNService
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:59: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class ExternalOpenVPNService
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:116: error: package IOpenVPNAPIService does not exist
    private final IOpenVPNAPIService.Stub mBinder = new IOpenVPNAPIService.Stub() {
                                    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:408: error: cannot find symbol
        private void sendUpdate(IOpenVPNStatusCallback broadcastItem,
                                ^
  symbol:   class IOpenVPNStatusCallback
  location: class OpenVPNServiceHandler
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ConfirmDialog.java:40: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ConfirmDialog.java:58: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class ConfirmDialog
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/RemoteAction.java:20: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/RemoteAction.java:29: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class RemoteAction
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/activities/DisconnectVPN.java:20: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/activities/DisconnectVPN.java:29: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class DisconnectVPN
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:61: error: package IServiceStatus does not exist
    private static final IServiceStatus.Stub mBinder = new IServiceStatus.Stub() {
                                                                         ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:64: error: cannot find symbol
        public ParcelFileDescriptor registerStatusCallback(IStatusCallbacks cb) throws RemoteException {
                                                           ^
  symbol: class IStatusCallbacks
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:112: error: cannot find symbol
        public void unregisterStatusCallback(IStatusCallbacks cb) throws RemoteException {
                                             ^
  symbol: class IStatusCallbacks
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:63: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:111: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:116: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:121: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:126: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:195: error: cannot find symbol
            RemoteCallbackList<IStatusCallbacks> callbacks;
                               ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusHandler
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNStatusService.java:204: error: cannot find symbol
                    IStatusCallbacks broadcastItem = callbacks.getBroadcastItem(i);
                    ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusHandler
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:105: error: package IOpenVPNServiceInternal does not exist
    private final IBinder mBinder = new IOpenVPNServiceInternal.Stub() {
                                                               ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:107: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:112: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:117: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:122: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:127: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:133: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:192: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:198: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:204: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:504: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java:732: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:31: error: package IStatusCallbacks does not exist
    private final IStatusCallbacks mCallback = new IStatusCallbacks.Stub() {
                                                                   ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:32: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:37: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:43: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:48: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:60: error: cannot find symbol
            IServiceStatus serviceStatus = IServiceStatus.Stub.asInterface(service);
            ^
  symbol: class IServiceStatus
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/StatusListener.java:60: error: package IServiceStatus does not exist
            IServiceStatus serviceStatus = IServiceStatus.Stub.asInterface(service);
                                                         ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:120: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:142: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:160: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:196: error: cannot find symbol
        final BlockingQueue<ExternalCertificateProvider> q = new LinkedBlockingQueue<>(1);
                            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/core/ExtAuthHelper.java:205: error: package ExternalCertificateProvider does not exist
                        q.put(ExternalCertificateProvider.Stub.asInterface(service));
                                                         ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/LaunchVPN.java:99: error: cannot find symbol
            IServiceStatus service = IServiceStatus.Stub.asInterface(binder);
            ^
  symbol: class IServiceStatus
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/LaunchVPN.java:99: error: package IServiceStatus does not exist
            IServiceStatus service = IServiceStatus.Stub.asInterface(binder);
                                                   ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:70: error: cannot find symbol
            mService = (IOpenVPNServiceInternal) (service);
                        ^
  symbol: class IOpenVPNServiceInternal
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:116: error: package IOpenVPNAPIService does not exist
    private final IOpenVPNAPIService.Stub mBinder = new IOpenVPNAPIService.Stub() {
                                                                          ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:278: error: cannot find symbol
        public void registerStatusCallback(IOpenVPNStatusCallback cb)
                                           ^
  symbol: class IOpenVPNStatusCallback
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:292: error: cannot find symbol
        public void unregisterStatusCallback(IOpenVPNStatusCallback cb)
                                             ^
  symbol: class IOpenVPNStatusCallback
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:118: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:156: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:167: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:199: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:204: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:210: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:235: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:243: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:256: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:266: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:277: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:291: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:300: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:307: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:314: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java:384: error: cannot find symbol
            RemoteCallbackList<IOpenVPNStatusCallback> callbacks;
                               ^
  symbol:   class IOpenVPNStatusCallback
  location: class OpenVPNServiceHandler
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/ConfirmDialog.java:63: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/api/RemoteAction.java:35: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
/Users/vishujain/Documents/VPN/node_modules/react-native-simple-openvpn/vpnLib/src/main/java/de/blinkt/openvpn/activities/DisconnectVPN.java:38: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
80 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vpnLib:compileUiDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Environment:**
 - OS: MACOS
 - react-native version:0.74.2
 - react-native-simple-openvpn version:2.1.1

**Comment by XiaoZ0108** [comment] 2024-06-16 06:30
same ,i need help,i had tried many solution in issue and complete ,but none of them success. OS:Window

**Comment by caferyukseloglu** [comment] 2024-08-03 17:46
![image](https://github.com/user-attachments/assets/eebccc86-ed6a-4b43-b8d5-c1a00adadec8)

**Comment by caferyukseloglu** [comment] 2024-08-04 00:11
@ccnnde Probabily this is issue for [ics-openvpn](https://github.com/schwabe/ics-openvpn)

**Comment by hamsterhomka** [comment] 2024-08-10 10:41
Hello guys. I have the same issue with `Task :vpnLib:compileUiDebugJavaWithJavac FAILED`.

Does anybody have a working example on expo? A link would be greatly appreciated! The expo version doesn't even matter; I just want to run it on android.

**Comment by Terciuss** [comment] 2024-08-11 20:03
Hello guys. The cause of the problem https://githubissues.com/facebook/react-native/45848

**Comment by SvetoslavKolpakov** [comment] 2024-08-15 23:29
Hello! Yes, you need to add the line in the gradle.build file in the VpnLib folder:
```gradle
android {
    //...
    build Features {
        aidl = true
    }
}
```
Then the error with aidl goes away. But now the problem is that it does not see the R class.
```bash
 error: cannot find symbol
      if (vpnProfile.checkProfile(reactContext) != R.string.no_error_found) {
                                                    ^
  symbol:   variable string
  location: class R
```

**Comment by SvetoslavKolpakov** [comment] 2024-08-15 23:36
> @ccnnde Probabily this is issue for [ics-openvpn](https://github.com/schwabe/ics-openvpn)

it's not connected in any way

**Comment by SvetoslavKolpakov** [comment] 2024-08-16 08:44
Now I have solved the problem with the R class too. To do this, you need to add this line to the `/node_modules/react-native-simple-openvpn/android/src/main/java/com/norcod/rnovpn/RNSimpleOpenvpnModule.java` file:
```java
import de.blinkt.openvpn.R;
```

**Comment by SvetoslavKolpakov** [comment] 2024-08-16 08:53
Only now the application abruptly closes when trying to connect to openvpn. At the same time, it does not output any logs. Here is an example of the code.
![code](https://github.com/user-attachments/assets/4f01156d-e296-41fc-b745-461e3b92aa92)

**Comment by TigranAvagyan18** [comment] 2024-09-03 13:46
> SvetoslavKolpakov

did u solve the issue?

**Comment by ccnnde** [comment] 2024-09-25 08:18
Please add these codes in the following file to temporarily resolve the issue; a new version will be released soon.

`node_modules/react-native-simple-openvpn/android/src/main/java/com/norcod/rnovpn/RNSimpleOpenvpnModule.java`

```java
import de.blinkt.openvpn.R;
```

`node_modules/react-native-simple-openvpn/vpnLib/build.gradle`

```
android {
    // ...
    buildFeatures {
        aidl = true
    }
}
```

`your-project/android/app/build.gradle`

```
android {
    // ...
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
```

**Comment by ccnnde** [comment] 2024-09-29 09:44
v2.1.2 has already fixed the issue.

**Closed by ccnnde** 2024-09-29 09:44 UTC
Labels: bug
