### ISSUE TITLE
Task :vpnLib:compileUiDebugAidl FAILED

### ISSUE THREAD

**Issue by Amoyens1s** [ccnnde/react-native-simple-openvpn#50] opened 2023-05-06 14:32 UTC
**Bug description:**
Task :vpnLib:compileUiDebugAidl FAILED

**To Reproduce:**
`yarn add react-native-simple-openvpn`
add config to setting.gradle, and then run
`yarn android`
got this error

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/37032347/236630291-cd9f434d-1999-4292-9adf-1a44a88381b3.png)

**Environment:**
 - OS: windows 10
 - OS version: 22H2
 - react-native version: 0.71.7
 - react-native-simple-openvpn version: 2.1.0

**Comment by xiaozhang0532** [comment] 2023-05-14 07:13
+1

**Comment by xiaozhang0532** [comment] 2023-05-14 07:13
@Amoyens1s do you find out the issues?

**Comment by Amoyens1s** [comment] 2023-05-17 06:31
> @Amoyens1s do you find out the issues?

nope, still got this.

**Comment by Intarial** [comment] 2023-06-16 14:31
@Amoyens1s, have you not bypassed this error yet? Maybe you replaced the library or what did you do?

**Comment by ccnnde** [comment] 2023-06-19 09:54
I cannot reproduce the issue on my Mac

**Comment by samovolkin-ms** [comment] 2023-06-29 10:22
This issue happened on Windows while on Mac it works fine without failures.

For me, downgrading `buildToolsVersion`  from `33.0.0` to `22.1.4` worked. Go to `android/build.gradle` – you'll see `buildToolsVersion` there.

Although, I'm not sure if it's the best solution but at least it runs now. Probably downgrading to other versions will work too.

**Comment by JoshMerlino** [comment] 2024-01-17 02:14
Add this to your main `build.gradle` No need to downgrade packages

```gradle
buildscript {
// ...
    ext {
        // ...
        kotlinVersion = findProperty('android.kotlinVersion') ?: '1.8.10'

    }

    dependencies {
        // ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}
```

**Comment by JoshMerlino** [comment] 2024-01-17 02:18
> > Add this to your main `build.gradle` No need to downgrade packages
> > ```groovy-gradle
> > buildscript {
> > // ...
> >     ext {
> >         // ...
> >         kotlinVersion = findProperty('android.kotlinVersion') ?: '1.8.10'
> > 
> >     }
> > 
> >     dependencies {
> >         // ...
> >         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
> >     }
> > }
> > ```
> 
> with expo ?

Yes

**Comment by JoshMerlino** [comment] 2024-01-17 03:09
> ### In last build failed with this error :
> ```
> Execution failed for task ':vpnLib:compileUiDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> ```

Already looking into this. It builds fine on both my windows and linux machines, but fails with that error on EAS.

I got some more specific info about whats failing on EAS
```
Task :vpnLib:compileUiDebugKotlin FAILED
e: file:///home/expo/workingdir/build/node_modules/react-native-simple-openvpn/vpnLib/src/ui/java/de/blinkt/openvpn/fragments/Utils.kt:38:9 'when' expression must be exhaustive, add necessary 'null' branch or 'else' branch instead
```

**Comment by ShadowEmperorYT** [comment] 2024-04-25 09:02
Anyone got any fix for this i am getting this error
```
> Task :vpnLib:compileUiDebugJavaWithJavac

> Task :vpnLib:compileUiDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
43 actionable tasks: 5 executed, 38 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\activities\DisconnectVPN.java:20: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\activities\DisconnectVPN.java:29: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class DisconnectVPN
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ConfirmDialog.java:40: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ConfirmDialog.java:58: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class ConfirmDialog
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:42: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:56: error: cannot find symbol
    final RemoteCallbackList<IOpenVPNStatusCallback> mCallbacks =
                             ^
  symbol:   class IOpenVPNStatusCallback
  location: class ExternalOpenVPNService
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:59: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class ExternalOpenVPNService
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:116: error: package IOpenVPNAPIService does not exist
    private final IOpenVPNAPIService.Stub mBinder = new IOpenVPNAPIService.Stub() {
                                    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:408: error: cannot find symbol
        private void sendUpdate(IOpenVPNStatusCallback broadcastItem,
                                ^
  symbol:   class IOpenVPNStatusCallback
  location: class OpenVPNServiceHandler
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\RemoteAction.java:20: error: cannot find symbol
import de.blinkt.openvpn.core.IOpenVPNServiceInternal;
                             ^
  symbol:   class IOpenVPNServiceInternal
  location: package de.blinkt.openvpn.core
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\RemoteAction.java:29: error: cannot find symbol
    private IOpenVPNServiceInternal mService;
            ^
  symbol:   class IOpenVPNServiceInternal
  location: class RemoteAction
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:22: error: cannot find symbol
import de.blinkt.openvpn.api.ExternalCertificateProvider;
                            ^
  symbol:   class ExternalCertificateProvider
  location: package de.blinkt.openvpn.api
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:248: error: cannot find symbol
        private final ExternalCertificateProvider service;
                      ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:252: error: cannot find symbol
                                                 ExternalCertificateProvider service) {
                                                 ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:263: error: cannot find symbol
        public ExternalCertificateProvider getService() {
               ^
  symbol:   class ExternalCertificateProvider
  location: class ExternalAuthProviderConnection
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:31: error: cannot find symbol
    private final IStatusCallbacks mCallback = new IStatusCallbacks.Stub() {
                  ^
  symbol:   class IStatusCallbacks
  location: class StatusListener
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:69: error: cannot find symbol
public class OpenVPNService extends VpnService implements StateListener, Callback, ByteCountListener, IOpenVPNServiceInternal {
                                                                                                      ^
  symbol: class IOpenVPNServiceInternal
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:37: error: cannot find symbol
    static final RemoteCallbackList<IStatusCallbacks> mCallbacks =
                                    ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusService
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:61: error: package IServiceStatus does not exist
    private static final IServiceStatus.Stub mBinder = new IServiceStatus.Stub() {
                                       ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:231: error: cannot find symbol
    private static void sendUpdate(IStatusCallbacks broadcastItem,
                                   ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusService
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\LaunchVPN.java:38: error: cannot find symbol
import de.blinkt.openvpn.core.IServiceStatus;
                             ^
  symbol:   class IServiceStatus
  location: package de.blinkt.openvpn.core
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\activities\DisconnectVPN.java:38: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ConfirmDialog.java:63: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:70: error: cannot find symbol
            mService = (IOpenVPNServiceInternal) (service);
                        ^
  symbol: class IOpenVPNServiceInternal
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:116: error: package IOpenVPNAPIService does not exist
    private final IOpenVPNAPIService.Stub mBinder = new IOpenVPNAPIService.Stub() {
                                                                          ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:278: error: cannot find symbol
        public void registerStatusCallback(IOpenVPNStatusCallback cb)
                                           ^
  symbol: class IOpenVPNStatusCallback
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:292: error: cannot find symbol
        public void unregisterStatusCallback(IOpenVPNStatusCallback cb)
                                             ^
  symbol: class IOpenVPNStatusCallback
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:118: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:156: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:167: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:199: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:204: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:210: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:235: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:243: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:256: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:266: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:277: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:291: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:300: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:307: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:314: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\ExternalOpenVPNService.java:384: error: cannot find symbol
            RemoteCallbackList<IOpenVPNStatusCallback> callbacks;
                               ^
  symbol:   class IOpenVPNStatusCallback
  location: class OpenVPNServiceHandler
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\api\RemoteAction.java:35: error: package IOpenVPNServiceInternal does not exist
            mService = IOpenVPNServiceInternal.Stub.asInterface(service);
                                              ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:120: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:142: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:160: error: cannot find symbol
            ExternalCertificateProvider externalAuthProvider = authProviderConnection.getService();
            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:196: error: cannot find symbol
        final BlockingQueue<ExternalCertificateProvider> q = new LinkedBlockingQueue<>(1);
                            ^
  symbol:   class ExternalCertificateProvider
  location: class ExtAuthHelper
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\ExtAuthHelper.java:205: error: package ExternalCertificateProvider does not exist
                        q.put(ExternalCertificateProvider.Stub.asInterface(service));
                                                         ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:31: error: package IStatusCallbacks does not exist
    private final IStatusCallbacks mCallback = new IStatusCallbacks.Stub() {
                                                                   ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:32: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:37: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:43: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:48: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:60: error: cannot find symbol
            IServiceStatus serviceStatus = IServiceStatus.Stub.asInterface(service);
            ^
  symbol: class IServiceStatus
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\StatusListener.java:60: error: package IServiceStatus does not exist
            IServiceStatus serviceStatus = IServiceStatus.Stub.asInterface(service);
                                                         ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:105: error: package IOpenVPNServiceInternal does not exist
    private final IBinder mBinder = new IOpenVPNServiceInternal.Stub() {
                                                               ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:107: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:112: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:117: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:122: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:127: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:133: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:192: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:198: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:204: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:504: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNService.java:732: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:61: error: package IServiceStatus does not exist
    private static final IServiceStatus.Stub mBinder = new IServiceStatus.Stub() {
                                                                         ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:64: error: cannot find symbol
        public ParcelFileDescriptor registerStatusCallback(IStatusCallbacks cb) throws RemoteException {
                                                           ^
  symbol: class IStatusCallbacks
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:112: error: cannot find symbol
        public void unregisterStatusCallback(IStatusCallbacks cb) throws RemoteException {
                                             ^
  symbol: class IStatusCallbacks
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:63: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:111: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:116: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:121: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:126: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:195: error: cannot find symbol
            RemoteCallbackList<IStatusCallbacks> callbacks;
                               ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusHandler
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\core\OpenVPNStatusService.java:204: error: cannot find symbol
                    IStatusCallbacks broadcastItem = callbacks.getBroadcastItem(i);
                    ^
  symbol:   class IStatusCallbacks
  location: class OpenVPNStatusHandler
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\LaunchVPN.java:99: error: cannot find symbol
            IServiceStatus service = IServiceStatus.Stub.asInterface(binder);
            ^
  symbol: class IServiceStatus
D:\Softwares\Proj\Venom\node_modules\react-native-simple-openvpn\vpnLib\src\main\java\de\blinkt\openvpn\LaunchVPN.java:99: error: package IServiceStatus does not exist
            IServiceStatus service = IServiceStatus.Stub.asInterface(binder);
                                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
80 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vpnLib:compileUiDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 9s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
```

**Comment by ShadowEmperorYT** [comment] 2024-04-25 09:22
@ccnnde please fix this. This is an error with windows i think

**Comment by caferyukseloglu** [comment] 2024-08-04 01:24
The iss persist here also https://github.com/ccnnde/react-native-simple-openvpn/issues/64

**Comment by leofmarciano** [comment] 2024-08-07 15:29
+1

**Comment by SvetoslavKolpakov** [comment] 2024-08-15 23:33
Hello! Yes, you need to add the line in the gradle.build file in the VpnLib folder:
```gradle
android {
    //...
    build Features {
        aidl = true
    }
}
```
Then the error with aidl goes away. But now the problem is that it does not see the R class.
```bash
 error: cannot find symbol
      if (vpnProfile.checkProfile(reactContext) != R.string.no_error_found) {
                                                    ^
  symbol:   variable string
  location: class R
```
OS: Linux mint
react-native version:0.74.3
react-native-simple-openvpn version:2.1.1Hello! Yes, you need to add the line in the gradle.build file in the VpnLib folder:
```gradle
android {
    //...
    build Features {
        aidl = true
    }
}
```
Then the error with aidl goes away. But now the problem is that it does not see the R class.
```bash
 error: cannot find symbol
      if (vpnProfile.checkProfile(reactContext) != R.string.no_error_found) {
                                                    ^
  symbol:   variable string
  location: class R
```
OS: Linux mint
react-native version:0.74.3
react-native-simple-openvpn version:2.1.1

**Comment by SvetoslavKolpakov** [comment] 2024-08-15 23:34
Hello! Yes, you need to add the line in the gradle.build file in the VpnLib folder:
```gradle
android {
    //...
    build Features {
        aidl = true
    }
}
```
Then the error with aidl goes away. But now the problem is that it does not see the R class.
```bash
 error: cannot find symbol
      if (vpnProfile.checkProfile(reactContext) != R.string.no_error_found) {
                                                    ^
  symbol:   variable string
  location: class R
```
OS: Linux mint
react-native version:0.74.3
react-native-simple-openvpn version:2.1.1

**Comment by SvetoslavKolpakov** [comment] 2024-08-16 08:55
Now I have solved the problem with the R class too. To do this, you need to add this line to the `/node_modules/react-native-simple-openvpn/android/src/main/java/com/norcod/rnovpn/RNSimpleOpenvpnModule.java` file:
```java
import de.blinkt.openvpn.R;
```
Only now the application abruptly closes when trying to connect to openvpn. At the same time, it does not output any logs. Here is an example of the code.
![code](https://github.com/user-attachments/assets/4f01156d-e296-41fc-b745-461e3b92aa92)

**Comment by ccnnde** [comment] 2024-09-29 09:55
v2.1.2 has already fixed the issue.

**Closed by ccnnde** 2024-09-29 09:55 UTC
Labels: bug

**Comment by ductridev** [comment] 2025-01-06 10:42
Hi @ccnnde, the error seem still there:
```
> Task :vpnLib:compileUiDebugJavaWithJavac FAILED
G:\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out\de\blinkt\openvpn\core\IStatusCallbacks.java:3: error: illegal unicode escape
 * Using: G:\AndroidStudioSDK\build-tools\35.0.0\aidl.exe -pG:\AndroidStudioSDK\platforms\android-35\framework.aidl -oG:\node_modules\react-native-simple-openvpn\vpnLib\build\generated\aidl_source_output_dir\uiDebug\out -IG:\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl -IG:\node_modules\react-native-simple-openvpn\vpnLib\src\ui\aidl -IG:\node_modules\react-native-simple-openvpn\vpnLib\src\debug\aidl -IG:\node_modules\react-native-simple-openvpn\vpnLib\src\uiDebug\aidl -IC:\Users\user\.gradle\caches\8.10.2\transforms\b3fbcacd889c2a72d50b53aa26f84c7c\transformed\core-1.6.0\aidl -IC:\Users\user\.gradle\caches\8.10.2\transforms\95d681e3d6e094f81686060cf3533488\transformed\versionedparcelable-1.1.1\aidl -dF:\aidl9811217791171606338.d G:\node_modules\react-native-simple-openvpn\vpnLib\src\main\aidl\de\blinkt\openvpn\core\IStatusCallbacks.aidl

21 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vpnLib:compileUiDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
 ```

My env:
react-native: 0.76.5
nodejs: 20.18.0
yarn: 1.22.22
os: window 10

My build.gradle:
```
buildscript {
    ext {
        buildToolsVersion = "35.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "27.1.12297006"
        kotlinVersion = "1.9.24"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.14")
    }
}

apply plugin: "com.facebook.react.rootproject"
```

I can confirm that I already enabled jniLibs as legacy packaging.
I can confirm that I already downloaded and unzipped jniLibs under G:\android\app\src\main\jniLibs.

**Comment by ccnnde** [comment] 2025-01-06 12:10
@ductridev https://github.com/ccnnde/react-native-simple-openvpn/issues/71#issuecomment-2466118045

**Comment by ductridev** [comment] 2025-01-07 01:53
@ccnnde oh cool, let me try that solution
